### ISSUE TITLE
Validation must take schemas directly from the repository

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-sdk-validation#112]
The validator stores the schemas locally e.g. in ~/.tng-schema/ … but it does not update them when they change. This is a major issue, since you do not notice this and validate against outdated local schemas.

The ideal solution would be to download schemas during installation and store them but also, during each validation, check if there is a new schema version to use:
* If there is, please replace the stored one with the new one and continue with the validation
* If there is not, please continue with the validation using the stored schemas.

cc @mpeuster

**Comment by mpeuster** [comment]
👍 

here is what I wrote:
Problem: Validator stores schemas locally e.g. in `~/.tng-schema/` but never updates them.

It should always try to download the latest version from GitHub and replace the local version with them (if not internet connection is available the the old ones can be used).

On top, the validator should log (level info) which schema files (path + date) it uses so a user finds this bug. Right now it is incredible complicated to find this :-/
