### ISSUE TITLE
Validate the change of schema in SLA descriptors

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-sdk-validation#136]
SLA descriptors are going to change its schema to make guarantees optional. The validator might need to be updated but before, we need to check if this new SLA format is supported from this tool. Test SLA validation when schemas are updated to support this new model and provide the required fixes in validator if required.

(Not implemented yet in the SLA manager)

Related to https://github.com/sonata-nfv/tng-portal/issues/306

**Comment by ekapassa** [comment]
@anapolg SLA manager can now support the optional guarantees and schema updated! The PR in `tng-schema` is open until Stefan or Manuel accept it.

**Comment by anapolg** [comment]
Ok thanks @ekapassa . Please @MiguelRivasQuobis keep track of this PR and test the validation of SLA still works whenever the PR is accepted (talk to Stefan, Manuel is out of office I think).

**Comment by MiguelRivasQuobis** [comment]
It works properly with the new sla schema.
