### ISSUE TITLE
Load test for validator

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-sdk-validation#143]

**Comment by MiguelRivasQuobis** [comment]
It is necessary:
  - To modify the validator to perform the syntax validation of all VNFDs when `tng-sdk-validate --project` is invoked.
  - To perform all non-functional tests and create the graphs
       - Link to statements to plot graphs: [link](https://github.com/sonata-nfv/tng-tests/blob/master/tests/SDK/test_sdk01_project_management/eval/eval_sdk01_project.ipynb).
  -
