### ISSUE TITLE
Define Validation API in OpenAPI format

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-sdk-validation#16]
In order to follow the parctices adopted in other 5GTANGO tools we should define the API this service in OpenAPI 3.0 (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md) format so that the doc can be generated automatically.

**Comment by jbonnet** [comment]
@antonroman We're not yet using v3.0 (OpenAPI) due to some limitations of tools used, but wwill in the future...

**Comment by antonroman** [comment]
Ok @jbonnet, thanks.  What version are you using?

**Comment by jbonnet** [comment]
Plain swagger 2.0.. Check [here](https://github.com/sonata-nfv/tng-gtk-common/blob/master/doc/swagger.json#L2). The `tng-lcm` and the `tng-sdk-package` are also using this version.
