### ISSUE TITLE
Add service and function integrity validation from son-cli

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-sdk-validation#24]
Functions ```_validate_service_integrity``` and ```_validate_function_integrity```  from son_cli/validate to valdiation.py script. The service and function object created by the object should be ready to check the integrity, however pay attention to potential differences from Sonata.

**Comment by danifernandezcalv** [comment]
Added functions from son-cli/validate.py in validator.py for integrity validation of services and functions
