### ISSUE TITLE
flask cache import issue

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-sdk-validation#35]
It seems we are experiencing this issue: https://github.com/thadeusb/flask-cache/issues/188

Modifying /usr/local/lib/python3.6/site-packages/flask_cache/jinja2ext.py fixes the issue. We must find the way to apply this fix to users when they install from scratch and track the issue to know when this is fixed in the library.

**Comment by danifernandezcalv** [comment]
Solved using flask_caching instead of flask_cache. (from flask.caching import Cache)
