### ISSUE TITLE
Add rules of all the different types to validator-custom-rules.yaml

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-sdk-validation#36]
Right now we have only numeric rules. We should include rules of all the different types documented here [business-rules](https://github.com/venmo/business-rules )
Namely: string, boolean, select and select_multiple

**Comment by anapolg** [comment]
Document the other types of custom rules supported with examples in the wiki! (@MiguelRivasQuobis )

**Comment by anapolg** [comment]
@MiguelRivasQuobis this and #96 are quick issues. Please do them before any other further development so that we can completely inform the users on how they work.
