### ISSUE TITLE
Possibility to send the descriptor as an attachment in REST POST

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-sdk-validation#48]
Currently it is necessary to send the PATH of the file to be able to perform a validation, the goal of this issues is to be able to send it as an attachment in the POST method for /validation endpoint. This way it can be easily used as a service and it will work when running in Docker.

**Comment by antonroman** [comment]
Please note that this was supported by son-cli so you can check the code there, and it is documented in the OpenAPI definition. To force this it is necessary to include the source query string parameter with value 'embedded'.

**Comment by danifernandezcalv** [comment]
Added two parameters to embeddend query:
-Descriptor: use to send the descriptor file.
-Rules: use to send the file with the custom rules (if the validation perform to validation this).
