### ISSUE TITLE
Minor issues in Project validation cli

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-sdk-validation#53]
just a couple of minor issues found in danifernandezcalv/tng-sdk-validation

When the folder passed as parameter in the project validation does not exist it finally says "No errors found in the Project":
06:33 $ tng-sdk-validate --project /home/anton/src/tng-sdk-validation-dani/tng-sdk-validation/src/tngsdk/validation/tests/samples/projects/test_pv_failure/ --workspace   /home/anton/src/tng-sdk-validation-dani/tng-sdk-validation/src/tngsdk/validation/tests/samples/projects/workspace/ -t
CLI input arguments: ['--project', '/home/anton/src/tng-sdk-validation-dani/tng-sdk-validation/src/tngsdk/validation/tests/samples/projects/test_pv_failure/', '--workspace', '/home/anton/src/tng-sdk-validation-dani/tng-sdk-validation/src/tngsdk/validation/tests/samples/projects/workspace/', '-t']
Printing all the arguments: Namespace(api=False, cfile=None, custom=False, dext=None, dpath=None, integrity=False, mode='stateless', nsd=None, package_file=None, project_path='/home/anton/src/tng-sdk-validation-dani/tng-sdk-validation/src/tngsdk/validation/tests/samples/projects/test_pv_failure/', service_address='127.0.0.1', service_port=5001, syntax=False, topology=True, verbose=False, vnfd=None, workspace_path='/home/anton/src/tng-sdk-validation-dani/tng-sdk-validation/src/tngsdk/validation/tests/samples/projects/workspace/')
Project validation
Syntax, integrity and topology validation
No errors found in the Project

On the other side, if the folder is passed without the final '/' it concatenates the source folder directly. In any case before merging these changes in master we'll have to check the complete structure.

Thanks Dani!

**Comment by danifernandezcalv** [comment]
Now when the folder passed does not exist the validation will print: 'Incorrect path. Try again with a correct project path' and leave the execution.
Can pass the directory paths now with '/' at the end or without it.
