### ISSUE TITLE
Expose REST API in container to integrate validation tool

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-sdk-validation#86]
User story related: [#361](https://git.cs.upb.de/5gtango/UserStories/issues/361)

**Comment by jbonnet** [comment]
@anapolg @antonroman @mpeuster @carlos-f-parada (CC @felipevicens)
I wonder where the Validator would enter the whole flow...
In SONATA we had it as a python library to be used in the SDK AND as a container to which the GK would pass the package before storing it in the Catalogue in the SP. This repetition was usefull given that a crazy developer might create the package by hand and submit it to the SP without validating it.

Now in SONATAv4.0 we have the (un-)packager. Should we keep the same logic and validate the package upon being submited to the V&V/SP? If so, should this validation occur before the call to the un-packager? But to validate the package we need to un-package it first, right? Should the unpackager call the validator instead? What dependencies do we have here, exactely?

**Comment by mpeuster** [comment]
Hi,

in my view the (un-)packager should call the validator. This has clear benefits:

1. GK only pushes the package to the unpackager and can be sure an validated result (or an error) is returned after unpackaging.
2. The packager can call the validator during packaging as well.

So my view is: We integrate the packager with the validator by directly calling the Python APIs of the validator. Other components, like GK get the validation feature "for free" if they use the packager.

Any objections?

**Comment by jbonnet** [comment]
Perfect!
THat was my idea as well...

**Comment by anapolg** [comment]
Same issue as https://github.com/sonata-nfv/tng-sdk-validation/issues/27
