### ISSUE TITLE
Support k8s descriptors validation

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-sdk-validation#87]
There is a new descriptor schema including k8s. The validation of these new descriptors fail since its a new structure not considered until now. Review the validation and adapt it to this new model.

**Comment by mpeuster** [comment]
Actually there is no schema yet; we first have to officially extend the schemas: https://github.com/sonata-nfv/tng-schema/issues/79 So you can use them to validate descriptors :-)
I have it on my todo.

**Comment by anapolg** [comment]
All schemas remain fully backwards compatible and we do not have to change any normal VNF.

CNNFD example in the wiki: 
https://github.com/sonata-nfv/tng-schema/wiki/CNF-VNFD-Example

The same example is also available in the repository:
https://github.com/sonata-nfv/tng-schema/blob/master/function-descriptor/examples/cnnf-vnfd.yml
