### ISSUE TITLE
CLI use creates a graphs/ folder

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-validation#92]
When using the validator on the command line, e.g.,  `tng-validate --project tng-smpilot-ns1-emulator/` it runs and creates a folder `graphs/` with some graphml files. The user won't know what to do with this, so we should hide it from him `.grpahs` or even better, create it somewehre in `/tmp` or so.

**Comment by mpeuster** [comment]
Examples: https://github.com/sonata-nfv/tng-industrial-pilot/tree/master/sdk-projects

**Comment by MiguelRivasQuobis** [comment]
I was using **comm-pilot** package, **graphs** doesn't apear in it. 
Now I am going to test with https://github.com/sonata-nfv/tng-industrial-pilot/tree/master/sdk-projects (tango-vrouter-haprx-svc).
